name: Release CI
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.22

      - name: Install deps
        run: bun i

      - name: CI
        run: bun run ci

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build

      - name: Release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
